# Generated by Django 5.0.10 on 2025-01-15 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='id_dominilio',
            new_name='id_domicilio',
        ),
        migrations.RemoveField(
            model_name='datos',
            name='id_domicilio',
        ),
        migrations.AddField(
            model_name='direccion',
            name='id_datos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.datos', verbose_name='Datos relacionados'),
        ),
    ]
