# Generated by Django 5.0.10 on 2025-01-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_rename_id_dominilio_direccion_id_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Constraseña'),
        ),
    ]
