# Generated by Django 5.0.10 on 2025-01-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_datos_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último inicio de sesión'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='datos',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contraseña'),
        ),
    ]
