# Generated by Django 5.0.10 on 2025-01-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_datos_last_login_alter_datos_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultorio',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del consultorio'),
        ),
    ]
