# Generated by Django 5.0.10 on 2025-01-15 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={},
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.tipousuario', verbose_name='Tipo de usuario'),
        ),
    ]
