# Generated by Django 5.0.10 on 2025-01-16 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_datos_last_login_alter_datos_email_and_more'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='id_consultorio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archives.consultorio', verbose_name='Consultorio'),
        ),
    ]
