# Generated by Django 5.0.10 on 2025-01-16 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_citas_id_consultorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='id_tratamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.tratamiento', verbose_name='Tratamiento'),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='id_receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.receta', verbose_name='Receta'),
        ),
    ]
