# Generated by Django 5.0.10 on 2025-01-16 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_alter_receta_id_tratamiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='id_receta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.receta', verbose_name='Receta'),
        ),
    ]
