# Generated by Django 5.0.10 on 2025-01-16 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_alter_diagnostico_id_receta'),
        ('users', '0002_alter_paciente_options_alter_paciente_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='estatus',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='id_tratamiento',
        ),
        migrations.AddField(
            model_name='receta',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='receta',
            name='id_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.doctor', verbose_name='Doctor'),
        ),
        migrations.AddField(
            model_name='receta',
            name='id_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='receta',
            name='receta_descripcion',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descripción de la receta'),
        ),
    ]
